# BundleGuard - Railway production inputs applicator
# 1. Copy docs/production-inputs.example.env to production.inputs.env
# 2. Fill SUPPORT_EMAIL, COMPANY_NAME, PRODUCTION_APP_URL (after Railway deploy)
# 3. Run: powershell -ExecutionPolicy Bypass -File .\scripts\apply-production-inputs.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
Set-Location $root

$inputsPath = Join-Path $root "production.inputs.env"
if (-not (Test-Path $inputsPath)) {
  Write-Host "Missing production.inputs.env" -ForegroundColor Yellow
  Write-Host "Copy docs/production-inputs.example.env to production.inputs.env and fill values."
  exit 1
}

$vars = @{}
Get-Content $inputsPath | ForEach-Object {
  if ($_ -match '^\s*([^#][^=]+)=(.*)$') {
    $vars[$matches[1].Trim()] = $matches[2].Trim()
  }
}

$missing = @()
foreach ($key in @("SUPPORT_EMAIL", "COMPANY_NAME", "PARTNER_OWNED_APP", "ROTATE_SECRETS_ACK")) {
  if (-not $vars[$key]) { $missing += $key }
}
if ($missing.Count -gt 0) {
  Write-Error ("Missing required inputs: " + ($missing -join ", "))
}

if ($vars["PARTNER_OWNED_APP"] -ne "true") {
  Write-Error "PARTNER_OWNED_APP must be true for live Shopify Billing (Partner-owned app)."
}

if ($vars["ROTATE_SECRETS_ACK"] -ne "true") {
  Write-Host "WARN: ROTATE_SECRETS_ACK is not true - rotate secrets before public launch." -ForegroundColor Yellow
}

$support = $vars["SUPPORT_EMAIL"]
$privacy = if ($vars["PRIVACY_EMAIL"]) { $vars["PRIVACY_EMAIL"] } else { $support }
$company = $vars["COMPANY_NAME"]
$policy = $vars["PRIVACY_POLICY_URL"]
$appUrl = $vars["PRODUCTION_APP_URL"]
$scopes = "read_products,write_products,read_inventory,read_locations,read_orders,write_app_proxy"

$lines = @(
  "# Generated by apply-production-inputs.ps1 - set these on Railway Variables"
  "# Do not commit this file with real secrets if you paste keys below."
  ""
  ("SUPPORT_EMAIL=" + $support)
  ("PRIVACY_EMAIL=" + $privacy)
  ("COMPANY_NAME=" + $company)
  ("PRIVACY_POLICY_URL=" + $policy)
  "SHOPIFY_BILLING_TEST=false"
  ("SCOPES=" + $scopes)
  ""
  "# Set after Railway gives you a public URL:"
  ("SHOPIFY_APP_URL=" + $appUrl)
  ""
  "# From Partner Dashboard / OpenAI (set in Railway UI):"
  "# SHOPIFY_API_KEY="
  "# SHOPIFY_API_SECRET="
  "# OPENAI_API_KEY="
  "# DATABASE_URL=  (auto from Railway Postgres plugin)"
)

$out = Join-Path $root "production.railway.vars.env"
[System.IO.File]::WriteAllText($out, ($lines -join "`n"))
Write-Host ("Wrote " + $out + " (gitignored - keep local only)") -ForegroundColor Green

$url = $vars["PRODUCTION_APP_URL"]
if ($url -and ($url -match '^https://') -and ($url -notmatch 'REPLACE_WITH|example\.com|localhost')) {
  & (Join-Path $PSScriptRoot "set-production-url.ps1") -Url $url
  Write-Host ("Shopify TOML + URL wiring updated for " + $url) -ForegroundColor Green
} else {
  Write-Host "PRODUCTION_APP_URL not set yet - deploy on Railway first, then re-run this script." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Inputs accepted. Next: follow docs/railway-deploy.md" -ForegroundColor Cyan
